name: github_search
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # utopia libs
  utopia_arch: ^0.5.0+4
  utopia_rest: ^0.1.0

  # architecture
  provider: ^6.0.1
  injector: ^2.0.0
  fast_immutable_collections: ^7.2.1

  # platform APIs

  # misc widgets
  flutter_svg: ^2.0.0+1
  smooth_page_indicator: ^1.1.0
  flutter_spinkit: ^5.2.0
  flutter_shakemywidget: ^1.0.5+1

  # misc utils
  intl: ^0.18.0

  # code generator runtimes
  freezed_annotation: ^2.2.0
  json_annotation: ^4.3.0
  flutter_sheet_localization: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generators
  freezed: ^2.3.2
  json_serializable: ^6.0.1
  build_runner: ^2.1.5
  flutter_sheet_localization_generator:
    git:
      url: https://github.com/Utopia-USS/flutter_sheet_localization.git
      path: flutter_sheet_localization_generator
      ref: deps_update

  # lint
  utopia_lints: ^0.0.1+1

dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: "NotoSansMono"
      fonts:
        - asset: assets/fonts/NotoSansMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansMono-Light.ttf
          weight: 300
